<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\Identity.Domain\Identity.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Roles\Commands\CreateRole\" />
    <Folder Include="Roles\Commands\AssignRole\" />
    <Folder Include="Roles\Queries\GetRoles\" />
    <Folder Include="Roles\Commands\UpdatePermissions\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

</Project>
